### ISSUE TITLE
Haas does not show warnings produced by code under test.

### ISSUE THREAD

**Issue by sjagoe** [scalative/haas#89]
```
$ python -m unittest discover
..............xx.....x..<path>:47: DeprecationWarning: Please use assertRegex instead.
  self.assertRegexpMatches(request.url, r'^.*?regex$')
......x.....x..................................<path>:341: DeprecationWarning: Please use assertRegex instead.
  result.output, r'.*?regex$')
.......................................................
----------------------------------------------------------------------
Ran 126 tests in 0.207s

OK (expected failures=5)
$ haas
........................................................................................x.....x...............xx.....x........
----------------------------------------------------------------------
Ran 126 tests in 0.224s

OK (expected failures=5)
```

**Comment by jvkersch** [comment]
I had a look at this and how the unittest module approaches warnings, and it seems like the latter initializes the warnings filter to `default` (unless the user explicitly specifies another set of warning options), causing 

@sjagoe Would you be interested in a patch that changed the default behavior of the `BaseTestRunner` to initialize `self.warnings` to `default`, with perhaps a command-line argument to turn this off?

**Comment by sjagoe** [comment]
@jvkersch Thanks for the offer.

Perhaps a command line option to set specific warning behaviour by the action name?
